### ISSUE TITLE
spent-addresses-db folder has no sst files

### ISSUE THREAD

**Issue by rav1112** [iotaledger/compass#115]
Exception in thread "main" com.iota.iri.service.spentaddresses.SpentAddressesException: spent-addresses-db folder has no sst files
        at com.iota.iri.service.snapshot.impl.SnapshotProviderImpl.assertSpentAddressesDbExist(SnapshotProviderImpl.java:246)
        at com.iota.iri.service.snapshot.impl.SnapshotProviderImpl.loadLocalSnapshot(SnapshotProviderImpl.java:212)
        at com.iota.iri.service.snapshot.impl.SnapshotProviderImpl.loadSnapshots(SnapshotProviderImpl.java:187)
        at com.iota.iri.service.snapshot.impl.SnapshotProviderImpl.init(SnapshotProviderImpl.java:102)
        at com.iota.iri.Iota.injectDependencies(Iota.java:204)
        at com.iota.iri.Iota.<init>(Iota.java:155)
        at com.iota.iri.IRI$IRILauncher.main(IRI.java:119)
        at com.iota.iri.IRI.main(IRI.java:60)

**Comment by alon-e** [comment]
this is a bug in IRI, you can either disable LOCAL_SNAPSHOTS or remove the meta files in generated - in any case you can find more information on our discord and in https://github.com/iotaledger/iri
