### ISSUE TITLE
Error while setting up private Tangle in IOTA

### ISSUE THREAD

**Issue by Ramya1405** [iotaledger/compass#140]
root@ip-172-31-7-149:/home/ubuntu/blockchain/iota/compass# bazel run //docker:layers_calculator
Extracting Bazel installation...
WARNING: Waiting for server process to terminate (waited 5 seconds, waiting at most 60)
Starting local Bazel server and connecting to it...
INFO: Analyzed target //docker:layers_calculator (134 packages loaded, 8113 targets configured).
INFO: Found 1 target...
INFO: Deleting stale sandbox base /root/.cache/bazel/_bazel_root/d087cd33acba26611b66dc42d10abf58/sandbox
ERROR: /root/.cache/bazel/_bazel_root/d087cd33acba26611b66dc42d10abf58/external/bazel_tools/tools/jdk/BUILD:316:1: Action external/bazel_tools/tools/jdk/platformclasspath.jar failed (Exit 1) java failed: error executing command external/remotejdk11_linux/bin/java -XX:+IgnoreUnrecognizedVMOptions '--add-exports=jdk.compiler/com.sun.tools.javac.platform=ALL-UNNAMED' -cp ... (remaining 4 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
Exception in thread "main" java.lang.IllegalArgumentException: external/local_jdk
        at jdk.compiler/com.sun.tools.javac.file.Locations$SystemModulesLocationHandler.isCurrentPlatform(Locations.java:1862)
        at jdk.compiler/com.sun.tools.javac.file.Locations$SystemModulesLocationHandler.update(Locations.java:1851)
        at jdk.compiler/com.sun.tools.javac.file.Locations$SystemModulesLocationHandler.handleOption(Locations.java:1798)
        at jdk.compiler/com.sun.tools.javac.file.Locations.handleOption(Locations.java:2062)
        at jdk.compiler/com.sun.tools.javac.file.BaseFileManager.handleOption(BaseFileManager.java:269)
        at jdk.compiler/com.sun.tools.javac.file.BaseFileManager$2.handleFileManagerOption(BaseFileManager.java:222)
        at jdk.compiler/com.sun.tools.javac.main.Option.process(Option.java:1138)
        at jdk.compiler/com.sun.tools.javac.main.Option.handleOption(Option.java:1086)
        at jdk.compiler/com.sun.tools.javac.file.BaseFileManager.handleOption(BaseFileManager.java:232)
        at jdk.compiler/com.sun.tools.javac.main.Arguments.doProcessArgs(Arguments.java:390)
        at jdk.compiler/com.sun.tools.javac.main.Arguments.processArgs(Arguments.java:347)
        at jdk.compiler/com.sun.tools.javac.main.Arguments.init(Arguments.java:246)
        at jdk.compiler/com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:185)
        at DumpPlatformClassPath.dumpJDK9AndNewerBootClassPath(DumpPlatformClassPath.java:106)
        at DumpPlatformClassPath.main(DumpPlatformClassPath.java:67)
Caused by: java.nio.file.NoSuchFileException: external/local_jdk
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.isSameFile(UnixFileSystemProvider.java:333)
        at java.base/java.nio.file.Files.isSameFile(Files.java:1530)
        at jdk.compiler/com.sun.tools.javac.file.Locations$SystemModulesLocationHandler.isCurrentPlatform(Locations.java:1860)
        ... 14 more
Target //docker:layers_calculator failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 17.368s, Critical Path: 0.59s
INFO: 4 processes: 4 linux-sandbox.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

**Comment by Ramya1405** [comment]
root@ip-172-31-7-149:/home/ubuntu/blockchain/iota/compass# python -V
Python 2.7.15+

root@ip-172-31-7-149:/home/ubuntu/blockchain/iota/compass# bazel --version
bazel 0.28.1

**Comment by Ramya1405** [comment]
Issue solved once JAVA_HOME path was set
export JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"
