### ISSUE TITLE
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:335:21

### ISSUE THREAD

**Issue by epm-bt** [iotaledger/compass#144]
I'm now having issues with my API to pull private data from Tangle. Has anyone else faced this?

It was working fine upto last couple of weeks!

```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:335:21
note: Run with `RUST_BACKTRACE=1` for a backtrace.
failed to parse:  5273168
```

Thank you!

**Comment by karimodm** [comment]
Sorry, what are you trying to do? How is it that Rust code is involved?

**Comment by epm-bt** [comment]
Just a typical Mam.fetch. See below

```
  const readMamPrivate = async () => {
    if (root == null){
      return "job does not exist";
    }

    if (root == ""){
      return "job pending diary";
    }
    
    // Get the data using the root and secret key
    var retrievedData = await Mam.fetch(root, "restricted", key);

    // New list for Ascii data
    var sensorData = [];

    // Convert the data from trytes to Ascii and save in new list
    for (var i = 0; i < retrievedData.messages.length; i++) {
      var trytes = retrievedData.messages[i];
      var trytesConverted = trytesToAscii(trytes);
      sensorData.push(trytesConverted);
    }

    // Returns the converted data
    return sensorData;
  };
```

**Comment by epm-bt** [comment]
Just a typical Mam.fetch call

```
  const readMamPrivate = async () => {
    // Get the data using the root and secret key
    var retrievedData = await Mam.fetch(root, "restricted", key);

    // New list for Ascii data
    var sensorData = [];

    // Convert the data from trytes to Ascii and save in new list
    for (var i = 0; i < retrievedData.messages.length; i++) {
      var trytes = retrievedData.messages[i];
      var trytesConverted = trytesToAscii(trytes);
      sensorData.push(trytesConverted);
    }

    // Returns the converted data
    return sensorData;
  };
```

**Comment by epm-bt** [comment]
And then the errors evolve to this, after couple of minutes (I suppose that's because my code polls for data every minute)

```
thread panicked while processing panic. aborting.
trap!
trap!
failed to parse:  abort("trap!"). Build with -s ASSERTIONS=1 for more info.

```

**Comment by GalRogozinski** [comment]
Closing it since this is not related to compass repo
Please ask for help on Discord or StackExchange
