### ISSUE TITLE
go_sdk error

### ISSUE THREAD

**Issue by Morteza14** [iotaledger/compass#148]
I am setting private tangle using https://docs.iota.org/docs/compass/0.1/how-to-guides/set-up-a-private-tangle and it works until this bazel run //docker:layers_calculator and when i run this i get this errors why this happens? and how do i fix it?
 INFO: Call stack for the definition of repository 'go_sdk' which is a _go_download_sdk (rule definition at /home/morteza/.cache/bazel/_bazel_morteza/dbf2462d898b371f7b7b0333556fafc0/external/io_bazel_rules_go/go/private/sdk.bzl:80:20):
 - /home/morteza/.cache/bazel/_bazel_morteza/dbf2462d898b371f7b7b0333556fafc0/external/io_bazel_rules_go/go/private/sdk.bzl:93:5
 - /home/morteza/.cache/bazel/_bazel_morteza/dbf2462d898b371f7b7b0333556fafc0/external/io_bazel_rules_go/go/private/sdk.bzl:261:13
 - /home/morteza/.cache/bazel/_bazel_morteza/dbf2462d898b371f7b7b0333556fafc0/external/io_bazel_rules_docker/repositories/go_repositories.bzl:34:5
 - /home/morteza/.cache/bazel/_bazel_morteza/dbf2462d898b371f7b7b0333556fafc0/external/io_bazel_rules_docker/repositories/deps.bzl:34:5
 - /home/morteza/compass/WORKSPACE:23:1
WARNING: Download from https://dl.google.com/go/go1.12.7.linux-amd64.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
ERROR: An error occurred during the fetch of repository 'go_sdk':
   Traceback (most recent call last):
	File "/home/morteza/.cache/bazel/_bazel_morteza/dbf2462d898b371f7b7b0333556fafc0/external/io_bazel_rules_go/go/private/sdk.bzl", line 78
		_remote_sdk(ctx, [url.format(filename) for url...], <2 more arguments>)
	File "/home/morteza/.cache/bazel/_bazel_morteza/dbf2462d898b371f7b7b0333556fafc0/external/io_bazel_rules_go/go/private/sdk.bzl", line 149, in _remote_sdk
		ctx.download(url = urls, sha256 = sha256, output ...")
java.io.IOException: Error downloading [https://dl.google.com/go/go1.12.7.linux-amd64.tar.gz] to /home/morteza/.cache/bazel/_bazel_morteza/dbf2462d898b371f7b7b0333556fafc0/external/go_sdk/go_sdk.tar.gz: GET returned 404 Not Found
INFO: Call stack for the definition of repository 'rules_cc' which is a http_archive (rule definition at /home/morteza/.cache/bazel/_bazel_morteza/dbf2462d898b371f7b7b0333556fafc0/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
 - /home/morteza/.cache/bazel/_bazel_morteza/dbf2462d898b371f7b7b0333556fafc0/external/bazel_tools/tools/build_defs/repo/utils.bzl:169:9
 - /DEFAULT.WORKSPACE.SUFFIX:276:1
ERROR: While resolving toolchains for target //docker:layers_calculator: invalid registered toolchain '@go_sdk//:go_android_386': no such package '@go_sdk//': Traceback (most recent call last):
	File "/home/morteza/.cache/bazel/_bazel_morteza/dbf2462d898b371f7b7b0333556fafc0/external/io_bazel_rules_go/go/private/sdk.bzl", line 78
		_remote_sdk(ctx, [url.format(filename) for url...], <2 more arguments>)
	File "/home/morteza/.cache/bazel/_bazel_morteza/dbf2462d898b371f7b7b0333556fafc0/external/io_bazel_rules_go/go/private/sdk.bzl", line 149, in _remote_sdk
		ctx.download(url = urls, sha256 = sha256, output ...")
java.io.IOException: Error downloading [https://dl.google.com/go/go1.12.7.linux-amd64.tar.gz] to /home/morteza/.cache/bazel/_bazel_morteza/dbf2462d898b371f7b7b0333556fafc0/external/go_sdk/go_sdk.tar.gz: GET returned 404 Not Found
ERROR: Analysis of target '//docker:layers_calculator' failed; build aborted: invalid registered toolchain '@go_sdk//:go_android_386': no such package '@go_sdk//': Traceback (most recent call last):
	File "/home/morteza/.cache/bazel/_bazel_morteza/dbf2462d898b371f7b7b0333556fafc0/external/io_bazel_rules_go/go/private/sdk.bzl", line 78
		_remote_sdk(ctx, [url.format(filename) for url...], <2 more arguments>)
	File "/home/morteza/.cache/bazel/_bazel_morteza/dbf2462d898b371f7b7b0333556fafc0/external/io_bazel_rules_go/go/private/sdk.bzl", line 149, in _remote_sdk
		ctx.download(url = urls, sha256 = sha256, output ...")
java.io.IOException: Error downloading [https://dl.google.com/go/go1.12.7.linux-amd64.tar.gz] to /home/morteza/.cache/bazel/_bazel_morteza/dbf2462d898b371f7b7b0333556fafc0/external/go_sdk/go_sdk.tar.gz: GET returned 404 Not Found
INFO: Elapsed time: 0.797s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets conf\
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets conf\
igured)
    currently loading: @bazel_tools//tools/jdk

**Comment by GalRogozinski** [comment]
Is it still happening?
It could be that #150 helped

**Comment by Morteza14** [comment]
thanks for your  help
the reason was internet connection!!!
and now i have aoother qusetions how can i run two or more iri on my private tangle???
