### ISSUE TITLE
Error: no native function or rule 'maven_jar'

### ISSUE THREAD

**Issue by arne-fuchs** [iotaledger/compass#153]
### Bug description
Error: no native function or rule 'maven_jar'

### Hardware Spec
Intel Xeon 5600 Series

### Steps To Reproduce
bazel run //docker:layers_calculator

### Errors
ERROR: Traceback (most recent call last):
	File "/home/arne/compass/WORKSPACE", line 42, column 11, in <toplevel>
		maven_jars()
	File "/home/arne/compass/third-party/maven_deps.bzl", line 3, column 11, in maven_jars
		native.maven_jar(
Error: no native function or rule 'maven_jar'
Available attributes: aar_import, action_listener, alias, android_binary, android_device, android_device_script_fixture, android_host_service_fixture, android_instrumentation_test, android_library, android_local_test, android_ndk_repository, android_sdk, android_sdk_repository, android_tools_defaults_jar, apple_binary, apple_cc_toolchain, apple_static_library, available_xcodes, bazel_version, bind, cc_binary, cc_host_toolchain_alias, cc_import, cc_libc_top_alias, cc_library, cc_proto_library, cc_test, cc_toolchain, cc_toolchain_alias, cc_toolchain_suite, config_feature_flag, config_setting, constraint_setting, constraint_value, environment, existing_rule, existing_rules, exports_files, extra_action, fdo_prefetch_hints, fdo_profile, filegroup, genquery, genrule, glob, j2objc_library, java_binary, java_import, java_library, java_lite_proto_library, java_package_configuration, java_plugin, java_proto_library, java_runtime, java_runtime_alias, java_test, java_toolchain, java_toolchain_alias, label_flag, label_setting, local_config_platform, local_repository, new_local_repository, ninja_build, ninja_graph, objc_import, objc_library, package_group, package_name, platform, proto_lang_toolchain, proto_library, py_binary, py_library, py_runtime, py_test, register_execution_platforms, register_toolchains, repository_name, sh_binary, sh_library, sh_test, test_suite, toolchain, toolchain_type, xcode_config, xcode_config_alias, xcode_version
ERROR: error loading package '': Encountered error while reading extension file 'protobuf_deps.bzl': no such package '@com_google_protobuf_deps//': error loading package 'external': Could not load //external package

**Comment by arne-fuchs** [comment]
Same error on a second system with ryzen 1700x and 32GB RAM

**Comment by arne-fuchs** [comment]
It was an old guide; closed the issue
