### ISSUE TITLE
Regression: jota.Transaction is not serializable.

### ISSUE THREAD

**Issue by alon-e** [iotaledger/compass#56]
https://github.com/iotaledger/compass/blob/612bc13b8e4e55850e3d043467c6b3b588f370ec/compass/conf/CoordinatorState.java#L40

replace with trytes themselves (Strings)
```
  public List<String> latestMilestoneTransactions;
```
```
      List<Transaction> latestMilestoneTransactions = db.createMilestone(trunk, branch, state.latestMilestoneIndex, config.MWM);
      state.latestMilestoneTransactions = latestMilestoneTransactions.stream().map(Transaction::toTrytes).collect(Collectors.toList());
      state.latestMilestoneHash = latestMilestoneTransactions.get(0).getHash();
```

**Comment by alon-e** [comment]
```
main] INFO org.iota.compass.Coordinator - storing index 16
[main] ERROR org.iota.compass.Coordinator - Error saving Compass state to file '//compass.state'!
java.io.NotSerializableException: jota.model.Transaction
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at java.util.ArrayList.writeObject(ArrayList.java:766)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1140)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at org.iota.compass.Coordinator.storeState(Coordinator.java:101)
	at org.iota.compass.Coordinator.start(Coordinator.java:339)
	at org.iota.compass.Coordinator.main(Coordinator.java:136)
Exception in thread "main" java.lang.RuntimeException: java.io.NotSerializableException: jota.model.Transaction
	at org.iota.compass.Coordinator.start(Coordinator.java:344)
	at org.iota.compass.Coordinator.main(Coordinator.java:136)
Caused by: java.io.NotSerializableException: jota.model.Transaction
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at java.util.ArrayList.writeObject(ArrayList.java:766)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1140)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at org.iota.compass.Coordinator.storeState(Coordinator.java:101)
	at org.iota.compass.Coordinator.start(Coordinator.java:339)
	... 1 more

```
the original error ^.
